### ISSUE TITLE
collaboration with ethereum propeller

### ISSUE THREAD

**Issue by adridadou** [swaldman/sbt-ethereum#10]
Hi, I wasn't sure how to contact you so I thought that this could be a good way to do it.
I'm the maintainer of eth-propeller, a jvm library to integrate smart contracts in your application.

It works with ethereumj & web3j (default) and has a facade in scala.

I was wondering if :
1. This could be interesting for you and your project
2. There is a possible collaboration here. I know that my license is more permissive than yours but we never know.

https://github.com/adridadou/eth-propeller-core
https://github.com/adridadou/eth-propeller-scala

Let me know if you're interested

**Comment by swaldman** [comment]
I am only now just seeing this!

(I am having a problem. I think I see notifications in conversations once I've particpated, but I'm not seeing notifications of Issues and Pull Requests to my own %@#$* repositories.)

I'm not sure if there's a straightforward collaboration, but I'm excited to talk, and glad to see more JVM-lang <=> Ethereum activity!

**Comment by swaldman** [comment]
This conversation seems long dormant, so I'm closing it. But I'm glad to talk any time. Please feel free to reopen it.
